### ISSUE TITLE
Build failures on FreeBSD

### ISSUE THREAD

**Issue by eserte** [michal-josef-spacek/Alien-DjVuLibre#4]
The build fails on all of my FreeBSD smokers. A sample report may be seen here: http://www.cpantesters.org/cpan/report/4348cfba-5af5-11ed-8b5d-073b6e8775ea

Just a guess: maybe the Makefiles except to be run with GNU make, not with BSD make.
Especially the error
```
/bin/sh: Syntax error: redirection unexpected (expecting word)
```
may indicate that some variable substitution or so did not work.

**Comment by michal-josef-spacek** [comment]
@eserte Thanks for report. I will look to it.

**Comment by michal-josef-spacek** [comment]
Fixes in https://github.com/michal-josef-spacek/Alien-DjVuLibre/commit/a7708831fb6217757f977c2f4385742a970977d2
